Rscript Druggability_LR.r
Rscript Druggability_CNN.r
Rscript Volume.r
Rscript Exposure.r
Rscript Pos.charged.r
Rscript Neg.charged.r
Rscript HBdonors.r
Rscript HBacceptors.r
Rscript Hydrophobic.r
Rscript Aromatic.r
python Merge.py
